name: Download and cache

on:
  workflow_call:
    inputs:
      urls:
        required: true
        type: string
      artifact-path:
        required: true
        type: string
      artifact-name:
        required: true
        type: string


jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ${{ fromJSON(inputs.urls) }}
    steps:
      - name: Download file
        run:
          curl --create-dirs --output-dir ${{ inputs.artifact-path }}s -O ${{ matrix.url }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 1