name: Release

on:
  push:
    branches:
      - feat/release-github-action

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ "windows-latest", "ubuntu-latest", "macos-latest" ]
        python-version: [ "3.9", "3.10", "3.11" ]
        include:
          - os: ubuntu-latest
            python-version: '3.11'
            sdist: true
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Fortran
        uses: awvwgk/setup-fortran@v1

      - name: Install build frontend
        run: python -m pip install --upgrade pip build

      - name: Build wheel
        run: python -I -m build --wheel

      - name: Build sdist
        if: ${{ matrix.sdist }}
        run: python -I -m build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 5
          if-no-files-found: error