name: Download from web and upload as artifact

on:
  workflow_call:
    inputs:
      urls:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ${{ fromJSON(inputs.urls) }}
    steps:
      - name: Download file
        run:
          curl --create-dirs --output-dir artifacts -O ${{ matrix.url }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: artifacts
          retention-days: 1